// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNPxhS3LxHhPCth5iBrVTs5rIKtlpF3XI',
    appId: '1:977613884661:web:3cff1c7bea705e190089bc',
    messagingSenderId: '977613884661',
    projectId: 'flutter-projects-4727c',
    authDomain: 'flutter-projects-4727c.firebaseapp.com',
    storageBucket: 'flutter-projects-4727c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjpsu7e4fkoDVlsnBr28Lk11c3vOx8yHU',
    appId: '1:977613884661:android:301389ff3527f7290089bc',
    messagingSenderId: '977613884661',
    projectId: 'flutter-projects-4727c',
    storageBucket: 'flutter-projects-4727c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgOJFB0UGRiHhD7_I9563tNDCj6Z7CpDY',
    appId: '1:977613884661:ios:e622183806c74f060089bc',
    messagingSenderId: '977613884661',
    projectId: 'flutter-projects-4727c',
    storageBucket: 'flutter-projects-4727c.firebasestorage.app',
    iosBundleId: 'com.carlosxfelipe.pushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgOJFB0UGRiHhD7_I9563tNDCj6Z7CpDY',
    appId: '1:977613884661:ios:36f2634a4d1939020089bc',
    messagingSenderId: '977613884661',
    projectId: 'flutter-projects-4727c',
    storageBucket: 'flutter-projects-4727c.firebasestorage.app',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNPxhS3LxHhPCth5iBrVTs5rIKtlpF3XI',
    appId: '1:977613884661:web:4aee6fe3523188fc0089bc',
    messagingSenderId: '977613884661',
    projectId: 'flutter-projects-4727c',
    authDomain: 'flutter-projects-4727c.firebaseapp.com',
    storageBucket: 'flutter-projects-4727c.firebasestorage.app',
  );
}
